import type { Metadata } from "next";
import './globals.css'
import localFont from "next/font/local";
import TopBar from "./pageComponents/TopBar";
import Footer from "./pageComponents/Footer";

import {Outfit} from 'next/font/google'


const myFont = localFont({
  src: [
    {
      path: "./fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-myfont", // creates a CSS variable
});

const outfit = Outfit({
  subsets:['latin'],
  weight:['400','500','600','700']
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={` ${outfit.className} min-h-screen relative dark:bg-black`}>
        <header className="h-[54px] w-full sticky top-0 z-10">
          <TopBar />
        </header>
        <main>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
